version: "3.8"
services:
  client:
    image: fc-retrieval-client:v1
    ports:
      - "80:80"
      - "443:443"
      - "8090:8090"
      - "8091:8091"
    networks:
      - shared
    depends_on: 
      - gateway
                
  gateway:
    image: fc-retrieval-gateway:v1
    networks:
      - shared
networks:
  shared:
