version: "3.8"
services:
  client:
    image: consensys/fc-retrieval-client:dev
    container_name: client
    command: /client --client-id=${CLIENT_ID} --ttl=${ESTABLISHMENT_TTL} --log-level=${LOG_LEVEL}
    ports:
      - "80:80"
      - "443:443"
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
    networks:
      - shared
    env_file:
      - .env

  dbg:
   image: busybox
   #image: radial/busyboxplus:curl
   container_name: dbg
   stdin_open: true
   tty: true
   networks:
     - shared
     
networks:
  shared:
    name: shared
    external: true
