# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

executors:
  executor_std:
    docker:
    # specify the version
    - image: circleci/golang:1.15
    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-client


commands:
  prepare:
    description: "Prepare"
    steps:
      - run:
          name: Check out Gateway and Provider
          command: |
            git clone https://github.com/ConsenSys/fc-retrieval-gateway.git ../fc-retrieval-gateway
            git --git-dir=../fc-retrieval-gateway/.git rev-parse HEAD > ../fc-retrieval-gateway/headcommit
            git clone https://github.com/ConsenSys/fc-retrieval-provider.git ../fc-retrieval-provider
            git --git-dir=../fc-retrieval-provider/.git rev-parse HEAD > ../fc-retrieval-provider/headcommit
            #      - checkout
            #      - run: git submodule init
            #      - run: git submodule update


jobs:
  unitTests:
    executor: executor_med
    steps:
      - prepare
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: 
        name: Build everything
        command: |
          make clean build
          cd ../fc-retrieval-gateway 
          make
      - run: make itest

  utest:
    executor: executor_med
    steps:
      - prepare
      - run: make utest

workflows:
  version: 2
  test_and_release:
    jobs:
      - utest
      - release

